#define NBR_OF_SWITCHES 6
#define BUTTON_DEBOUNCE_DELAY 50

#define XMIN_SWITCH_PIN 2
#define XMAX_SWITCH_PIN 3
#define YMIN_SWITCH_PIN 4
#define YMAX_SWITCH_PIN 5
#define ZMIN_SWITCH_PIN 6
#define ZMAX_SWITCH_PIN 7

#define ESTOP_BUTTON_PIN 7
